language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - rbx-19mode
  - jruby
  - ree

matrix:
  allow_failures:
    - rvm: ruby-head

 before_install:
  - gem update --system 2.1.11
  - gem install bundler
